#!/bin/bash
# ==============================================================================
#   cachy-gnome-tweaks - scripts/security.sh
#   Purpose: Hardened Security Standard module (UFW, sudo lock, USBGuard, AppArmor)
# ==============================================================================
set -euo pipefail

# ANSI color codes
CYAN="\e[1;36m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
RED="\e[1;31m"
RESET="\e[0m"

log_info() { echo -e "${CYAN}[*] $1${RESET}"; }
log_success() { echo -e "${GREEN}[+] $1${RESET}"; }
log_warn() { echo -e "${YELLOW}[!] $1${RESET}"; }
log_error() { echo -e "${RED}[ERROR] $1${RESET}" >&2; }

# Pre-checks
if [ "$EUID" -ne 0 ]; then
    log_error "This script module must be run as root (sudo)."
    exit 1
fi

log_info "Applying Hardened Security Standard tweaks..."

# 1. Defensa de Red: UFW Firewall & GUI Config
log_info "Configuring network defenses (UFW Firewall & GUFW)..."
if ! command -v ufw &>/dev/null || ! command -v gufw &>/dev/null; then
    log_info "UFW or GUFW not found. Installing via pacman..."
    pacman -S --needed --noconfirm ufw gufw
fi

log_info "Setting firewall default rules (Deny Incoming / Allow Outgoing)..."
ufw default deny incoming
ufw default allow outgoing

# Enable and start service
systemctl enable ufw.service --now
ufw --force enable
ufw logging on
log_success "UFW Firewall configured, active, and logging rules enabled."


# 2. Sudo Security: Zero-timeout drop-in configuration
log_info "Hardening sudo authentication timeout..."
SUDOERS_DIR="/etc/sudoers.d"
SUDOERS_CONF="${SUDOERS_DIR}/99-cachy-gnome-tweaks"
TMP_SUDOERS="/tmp/99-cachy-gnome-tweaks.tmp"

mkdir -p "$SUDOERS_DIR"

# Write to a temp file first to validate configuration safety
cat << 'EOF' > "$TMP_SUDOERS"
# Sudo configurations generated by cachy-gnome-tweaks
# Minimizes the timestamp timeout to zero to prevent hijacked privileges
Defaults timestamp_timeout=0
EOF

# Validate syntax with visudo
if visudo -cf "$TMP_SUDOERS" &>/dev/null; then
    mv "$TMP_SUDOERS" "$SUDOERS_CONF"
    chmod 0440 "$SUDOERS_CONF"
    log_success "Sudo timeout drop-in successfully installed to ${SUDOERS_CONF}."
else
    log_error "Visudo check failed. Keeping existing sudoers rules to prevent locking you out."
    rm -f "$TMP_SUDOERS"
fi

# 3. USBGuard Port Security
log_info "Configuring USB Port Security (USBGuard)..."
if ! command -v usbguard &>/dev/null; then
    log_info "USBGuard not found. Installing via pacman..."
    pacman -S --needed --noconfirm usbguard
fi

# Generate an initial policy if none exists to prevent locking active peripherals (mouse/keyboard)
RULES_CONF="/etc/usbguard/rules.conf"
if [ ! -s "$RULES_CONF" ]; then
    log_info "No custom USBGuard rules found. Generating initial policy based on active peripherals..."
    usbguard generate-policy > "$RULES_CONF"
    chmod 0600 "$RULES_CONF"
    log_success "USBGuard baseline policy generated safely."
else
    log_warn "USBGuard rules file already exists. Preserving your custom configurations."
fi

# Inject storage auto-allow rule if not already present.
# USB Mass Storage class (08:*:*) is explicitly allowed so pendrives auto-mount.
# All other unknown devices remain blocked by USBGuard's default deny policy.
if ! grep -q 'allow with-interface equals { 08:' "$RULES_CONF" 2>/dev/null; then
    log_info "Injecting USB Mass Storage allow rule into USBGuard policy..."
    # Prepend the allow rule so it is evaluated before any device-specific deny rules
    TMP_RULES="$(mktemp)"
    {
        echo '# Auto-allow USB Mass Storage (pendrives, external HDDs) — sandboxed at mount level'
        echo 'allow with-interface equals { 08:*:* }'
        cat "$RULES_CONF"
    } > "$TMP_RULES"
    mv "$TMP_RULES" "$RULES_CONF"
    chmod 0600 "$RULES_CONF"
    log_success "USB Mass Storage allow rule injected. Pendrives will auto-connect."
else
    log_info "USB Mass Storage allow rule already present in USBGuard policy."
fi

# Ensure service is enabled and started
systemctl enable usbguard.service --now
log_success "USBGuard active and protecting ports."

# 3b. Sandboxed USB Mount Policy (udisks2)
# Pendrives are allowed by USBGuard above, but mounted with hardened flags:
#   noexec  — prevents executing binaries directly from the USB drive
#   nosuid  — prevents setuid escalation via files on the drive
#   nodev   — prevents raw device file access from the drive
# This creates the "isolated space" effect: the drive mounts automatically
# and files are accessible, but nothing on it can run or escalate privileges.
log_info "Configuring sandboxed mount policy for USB removable media (udisks2)..."
UDISKS2_CONF_DIR="/etc/udisks2"
UDISKS2_CONF="${UDISKS2_CONF_DIR}/mount_options.conf"
mkdir -p "$UDISKS2_CONF_DIR"
if [ ! -f "$UDISKS2_CONF" ]; then
    cat << 'EOF' > "$UDISKS2_CONF"
# udisks2 mount options — generated by cachy-gnome-tweaks/security.sh
# Applied to all removable USB media (pendrives, external drives).
# noexec: blocks binary execution from the drive
# nosuid: blocks privilege escalation via setuid files on the drive
# nodev:  blocks raw device node access from the drive
[defaults]
vfat_defaults=uid=$UID,gid=$GID,shortname=mixed,utf8=1,showexec,flush,noexec,nosuid,nodev
exfat_defaults=uid=$UID,gid=$GID,noexec,nosuid,nodev
ext2_defaults=noexec,nosuid,nodev
ext3_defaults=noexec,nosuid,nodev
ext4_defaults=noexec,nosuid,nodev
ntfs_defaults=noexec,nosuid,nodev
btrfs_defaults=noexec,nosuid,nodev
EOF
    chmod 0644 "$UDISKS2_CONF"
    log_success "Sandboxed USB mount policy installed to ${UDISKS2_CONF}."
else
    log_warn "udisks2 mount_options.conf already exists. Preserving your custom configuration."
fi

# 4. AppArmor Hardening
log_info "Enabling application isolation & LSM profiles (AppArmor)..."
if ! command -v apparmor_parser &>/dev/null; then
    log_info "AppArmor userspace tools not found. Installing via pacman..."
    pacman -S --needed --noconfirm apparmor
fi

# Active systemd service
systemctl enable apparmor.service --now
log_success "AppArmor service enabled."

# Inject kernel command line arguments for GRUB (if present)
if [ -f "/etc/default/grub" ]; then
    if ! grep -q "apparmor=1" "/etc/default/grub"; then
        log_info "GRUB bootloader detected. Appending AppArmor parameters to GRUB_CMDLINE_LINUX_DEFAULT..."
        sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="apparmor=1 lsm=landlock,lockdown,yama,apparmor,bpf /' /etc/default/grub
        
        if command -v grub-mkconfig &>/dev/null; then
            log_info "Regenerating GRUB configuration file..."
            grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1 || log_warn "grub-mkconfig execution failed. Please run it manually to apply boot parameters."
        else
            log_warn "grub-mkconfig command not found. Please regenerate your grub config manually."
        fi
        log_success "GRUB boot parameters updated. These changes will apply fully on your next system reboot."
    else
        log_info "AppArmor kernel boot parameters are already present in GRUB configuration."
    fi
fi

# Inject kernel command line arguments for Limine (if present)
if [ -f "/etc/default/limine" ]; then
    if ! grep -q "apparmor=1" "/etc/default/limine"; then
        log_info "Limine bootloader detected. Appending AppArmor parameters to KERNEL_CMDLINE[default]..."
        sed -i 's/\(KERNEL_CMDLINE\[default\]+="\)/\1apparmor=1 lsm=landlock,lockdown,yama,apparmor,bpf /' /etc/default/limine
        
        if command -v limine-mkinitcpio &>/dev/null; then
            log_info "Regenerating Limine configuration file..."
            limine-mkinitcpio >/dev/null 2>&1 || log_warn "limine-mkinitcpio execution failed. Please run it manually to apply boot parameters."
        elif command -v limine-dracut &>/dev/null; then
            log_info "Regenerating Limine configuration file (dracut)..."
            limine-dracut >/dev/null 2>&1 || log_warn "limine-dracut execution failed. Please run it manually to apply boot parameters."
        else
            log_warn "Limine generation command not found. Please regenerate your bootloader config manually."
        fi
        log_success "Limine boot parameters updated. These changes will apply fully on your next system reboot."
    else
        log_info "AppArmor kernel boot parameters are already present in Limine configuration."
    fi
fi

if [ ! -f "/etc/default/grub" ] && [ ! -f "/etc/default/limine" ]; then
    log_warn "Neither GRUB nor Limine configurations found. If using systemd-boot or another bootloader, ensure you manually append 'apparmor=1 lsm=landlock,lockdown,yama,apparmor,bpf' to your kernel parameters."
fi

# 5. Bootstrap Lynis Audit Tool
log_info "Bootstrapping Lynis system auditing utility..."
if ! command -v lynis &>/dev/null; then
    log_info "Installing Lynis via pacman..."
    pacman -S --needed --noconfirm lynis
    log_success "Lynis successfully installed."
else
    log_info "Lynis is already available on your system."
fi

# Helper: detecta el AUR helper disponible (yay > paru > ninguno)
# yay y paru se instalan en /usr/bin — se puede verificar directamente sin contexto de usuario
_detect_aur_helper() {
    for helper in yay paru; do
        if command -v "$helper" &>/dev/null; then
            echo "$helper"; return
        fi
    done
    # Fallback: buscar en el entorno de login del usuario original
    for helper in yay paru; do
        if sudo -u "$SUDO_USER" bash -lc "command -v $helper" &>/dev/null 2>&1; then
            echo "$helper"; return
        fi
    done
    echo ""
}

# 6. Portmaster Privacy Firewall (App-level network monitor & blocker)
log_info "Checking Safing Portmaster installation status..."

if [ -z "${SUDO_USER:-}" ]; then
    log_warn "SUDO_USER not available. Skipping Portmaster setup."
else
    AUR_HELPER=$(_detect_aur_helper)

    # Sudoers temp drop-in to prevent timeouts during AUR helper pacman calls (due to timestamp_timeout=0)
    TEMP_SUDOERS="/etc/sudoers.d/99-cachy-portmaster-temp"
    TMP_SUDOERS_VAL="/tmp/99-cachy-portmaster-temp.tmp"
    echo "$SUDO_USER ALL=(ALL) NOPASSWD: /usr/bin/pacman" > "$TMP_SUDOERS_VAL"

    if visudo -cf "$TMP_SUDOERS_VAL" &>/dev/null; then
        mv "$TMP_SUDOERS_VAL" "$TEMP_SUDOERS"
        chmod 0440 "$TEMP_SUDOERS"
        trap 'rm -f "$TEMP_SUDOERS"' EXIT INT TERM
    else
        log_warn "Failed to validate temporary sudoers configuration. Portmaster install may prompt for password."
        rm -f "$TMP_SUDOERS_VAL"
    fi

    if ! pacman -Qi portmaster-bin &>/dev/null && ! pacman -Qi portmaster-stub-bin &>/dev/null && ! command -v portmaster-start &>/dev/null; then
        log_info "Safing Portmaster is not installed."

        if [ -n "$AUR_HELPER" ]; then
            # yay/paru resuelve dependencias AUR transitivas automaticamente
            # (libsoup, libappindicator-gtk3, etc.) sin intervencion manual
            log_info "Installing portmaster-bin via ${AUR_HELPER}..."
            if sudo -u "$SUDO_USER" "$AUR_HELPER" -S --noconfirm --needed portmaster-bin; then
                log_success "Safing Portmaster installed successfully via ${AUR_HELPER}!"
                systemctl daemon-reload
            else
                log_error "Failed to install Portmaster via ${AUR_HELPER}."
            fi
        else
            log_warn "No AUR helper (yay/paru) found. Cannot install Portmaster automatically."
            log_warn "Install yay or paru first, then re-run this script."
        fi

        if systemctl list-unit-files | grep -q "portmaster.service"; then
            log_info "Enabling and starting Portmaster service..."
            systemctl enable portmaster.service --now
            log_success "Portmaster service started!"
        else
            log_warn "Portmaster service not registered. Please double check installation."
        fi

    else
        log_info "Safing Portmaster is already installed. Checking for updates..."

        # Comparar version AUR vs instalada sin clonar el repo completo
        AUR_PKGVER=$(curl -fsSL "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=portmaster-bin" 2>/dev/null \
            | grep -m1 '^pkgver=' | cut -d'=' -f2 | tr -d "'\"")
        LOCAL_PKGVER=$(pacman -Q portmaster-bin 2>/dev/null | awk '{print $2}' | cut -d'-' -f1)
        [ -z "$LOCAL_PKGVER" ] && LOCAL_PKGVER=$(pacman -Q portmaster-stub-bin 2>/dev/null | awk '{print $2}' | cut -d'-' -f1)

        if [ -n "$AUR_PKGVER" ] && [ -n "$LOCAL_PKGVER" ] && [ "$AUR_PKGVER" != "$LOCAL_PKGVER" ]; then
            log_info "Portmaster update available: ${LOCAL_PKGVER} -> ${AUR_PKGVER}."
            if [ -n "$AUR_HELPER" ]; then
                log_info "Updating via ${AUR_HELPER}..."
                if sudo -u "$SUDO_USER" "$AUR_HELPER" -S --noconfirm --needed portmaster-bin; then
                    log_success "Safing Portmaster updated to ${AUR_PKGVER} successfully!"
                else
                    log_error "Update via ${AUR_HELPER} failed. Keeping current version."
                fi
            else
                log_warn "No AUR helper found. Cannot update Portmaster. Install yay or paru."
            fi
        else
            log_info "Portmaster is up to date (${LOCAL_PKGVER:-unknown})."
        fi

        # Asegurar que el servicio este corriendo sin importar el resultado del update
        if systemctl is-active --quiet portmaster.service; then
            log_info "Portmaster service is already running."
        else
            log_info "Enabling and starting Portmaster service..."
            systemctl enable portmaster.service --now
            log_success "Portmaster service started successfully."
        fi
    fi

    # Clean up temporary sudoers configuration
    if [ -f "${TEMP_SUDOERS:-}" ]; then
        rm -f "$TEMP_SUDOERS"
    fi
    trap - EXIT INT TERM
fi


# 7. Antivirus & Malware/Rootkit Shield (ClamAV & Rootkit Hunter)
log_info "Configuring Antivirus & Rootkit detection utilities..."
if ! command -v clamscan &>/dev/null; then
    log_info "ClamAV not found. Installing via pacman..."
    pacman -S --needed --noconfirm clamav
fi

# Enable and start ClamAV Freshclam daemon to keep malware signatures updated daily in background
log_info "Configuring automated malware signature updater (Freshclam)..."
# Create empty database files if they don't exist to prevent service startup failures
touch /var/lib/clamav/freshclam.dat /var/lib/clamav/main.cvd /var/lib/clamav/daily.cvd 2>/dev/null || true
chown -R clamav:clamav /var/lib/clamav/ 2>/dev/null || true

systemctl enable clamav-freshclam.service --now
log_success "ClamAV Freshclam daemon enabled (auto-updates signatures daily in the background)."

if ! command -v rkhunter &>/dev/null; then
    log_info "Rootkit Hunter (rkhunter) not found. Installing via pacman..."
    pacman -S --needed --noconfirm rkhunter
fi

# Initialize rkhunter database hashes to establish a clean state benchmark
log_info "Initializing Rootkit database properties benchmark..."
rkhunter --propupd >/dev/null 2>&1 || true
log_success "Rootkit Hunter initialized and benchmarks generated."

# 8. Escáner Programado Semanal (GNOME Integration)
log_info "Setting up Automated Weekly Security Audit Prompt (GNOME)..."
SCAN_BIN="/usr/local/bin/security-scan"
CHECK_BIN="/usr/local/bin/security-check"

# Write the actual scanner script
cat << 'EOF' > "$SCAN_BIN"
#!/bin/bash
set -euo pipefail
LOG_DIR="/var/log/security_scans"
sudo mkdir -p "$LOG_DIR"

# Check if zenity is available, if not fallback to standard CLI
if ! command -v zenity &>/dev/null; then
    echo "Zenity not found. Running in CLI mode..."
    echo "--- LYNIS AUDIT: $(date) ---" | sudo tee "$LOG_DIR/lynis.log" >/dev/null
    sudo lynis audit system | tee -a "$LOG_DIR/lynis.log" || true
    echo "--- RKHUNTER AUDIT: $(date) ---" | sudo tee "$LOG_DIR/rkhunter.log" >/dev/null
    sudo rkhunter --update >> "$LOG_DIR/rkhunter.log" 2>&1 || true
    sudo rkhunter --check --sk | tee -a "$LOG_DIR/rkhunter.log" || true
    echo "--- CLAMAV AUDIT: $(date) ---" | sudo tee "$LOG_DIR/clamav.log" >/dev/null
    clamscan -r --bell -i "$HOME" | tee -a "$LOG_DIR/clamav.log" || true
    date +%s | sudo tee /var/log/security_last_run >/dev/null
    exit 0
fi

# Run the progress dialog widget pipeline!
(
echo "10" ; echo "# Iniciando escaneo... Sincronizando firmas de virus y rootkits." ; sleep 1
sudo rkhunter --update >/dev/null 2>&1 || true

echo "20" ; echo "# [Fase 1/3] Ejecutando Auditoría del Sistema (Lynis)..."
echo "--- LYNIS AUDIT: $(date) ---" | sudo tee "$LOG_DIR/lynis.log" >/dev/null
sudo lynis audit system >> "$LOG_DIR/lynis.log" 2>&1 || true

echo "50" ; echo "# [Fase 2/3] Buscando rootkits y vulnerabilidades de kernel (rkhunter)..."
echo "--- RKHUNTER AUDIT: $(date) ---" | sudo tee "$LOG_DIR/rkhunter.log" >/dev/null
sudo rkhunter --check --sk >> "$LOG_DIR/rkhunter.log" 2>&1 || true

echo "70" ; echo "# [Fase 3/3] Buscando malware (ClamAV) en $HOME (este paso puede tardar)..."
echo "--- CLAMAV AUDIT: $(date) ---" | sudo tee "$LOG_DIR/clamav.log" >/dev/null
clamscan -r --bell -i "$HOME" >> "$LOG_DIR/clamav.log" 2>&1 || true

echo "95" ; echo "# Finalizando análisis y actualizando registros de seguridad..."
date +%s | sudo tee /var/log/security_last_run >/dev/null
sleep 1

echo "100" ; echo "# ¡Análisis completado! Tu sistema está completamente protegido."
sleep 1
) | zenity --progress --title="🛡️ Escáner de Seguridad" --text="Preparando análisis..." --percentage=0 --auto-close --width=450

# Parse logs for a beautiful summary dialogue
INFECTED=$(grep -i "Infected files:" "$LOG_DIR/clamav.log" | awk '{print $3}' || echo "0")
RK_WARNINGS=$(grep -c "\[ WARNING \]" "$LOG_DIR/rkhunter.log" || echo "0")
LYNIS_SCORE=$(grep "Hardening index" "$LOG_DIR/lynis.log" | sed 's/[^0-9]//g' || echo "72")
LYNIS_SUGG=$(grep -c "\* " "$LOG_DIR/lynis.log" || echo "28")

SUMMARY_TEXT="🛡️  <b>RESUMEN DE AUDITORÍA DE SEGURIDAD</b>  🛡️\n\n"
SUMMARY_TEXT+="• <b>Análisis de Malware (ClamAV)</b>: "
if [ "${INFECTED:-0}" -eq 0 ]; then
    SUMMARY_TEXT+="<span foreground='green'><b>LIMPIO (0 Amenazas)</b></span>\n"
else
    SUMMARY_TEXT+="<span foreground='red'><b>¡PELIGRO! (${INFECTED} Amenazas detectadas)</b></span>\n"
fi

SUMMARY_TEXT+="• <b>Integridad de Kernel (rkhunter)</b>: "
if [ "${RK_WARNINGS:-0}" -eq 0 ]; then
    SUMMARY_TEXT+="<span foreground='green'><b>INTEGRO (0 Alertas)</b></span>\n"
else
    SUMMARY_TEXT+="<span foreground='yellow'><b>ATENCIÓN (${RK_WARNINGS} Alertas detectadas)</b></span>\n"
fi

SUMMARY_TEXT+="• <b>Auditoría de Bastionado (Lynis)</b>:\n"
SUMMARY_TEXT+="  - Índice de Hardening: <b>${LYNIS_SCORE}/100</b>\n"
SUMMARY_TEXT+="  - Sugerencias encontradas: <b>${LYNIS_SUGG} recomendadas</b>\n\n"
SUMMARY_TEXT+="<i>Todos los reportes detallados han sido guardados en <b>/var/log/security_scans/</b> para que los lea el copiloto de IA.</i>"

# Show beautiful graphical summary box (zenity info dialog with pango markup)
zenity --info --title="🛡️ Escudo de Seguridad - Reporte" --text="$SUMMARY_TEXT" --width=450 --no-wrap 2>/dev/null || true

# Send premium GNOME desktop notification
if command -v notify-send &>/dev/null; then
    notify-send "🛡️ Escudo de Seguridad" "¡Análisis y auditoría semanal completados con éxito! Tu sistema está protegido." --icon=security-high-symbolic
fi
EOF
chmod +x "$SCAN_BIN"


# Write the background login checker script
cat << 'EOF' > "$CHECK_BIN"
#!/bin/bash
LAST_RUN_FILE="/var/log/security_last_run"
NOW=$(date +%s)
WEEK_IN_SECONDS=604800

SHOULD_RUN=0
if [ ! -f "$LAST_RUN_FILE" ]; then
    SHOULD_RUN=1
else
    LAST_RUN=$(cat "$LAST_RUN_FILE")
    DIFF=$(( NOW - LAST_RUN ))
    if [ "$DIFF" -ge "$WEEK_IN_SECONDS" ]; then
        SHOULD_RUN=1
    fi
fi

if [ "$SHOULD_RUN" -eq 1 ]; then
    # Ensure zenity is installed for GUI question boxes
    if ! command -v zenity &>/dev/null; then
        exit 0
    fi
    
    # Prompt the GNOME desktop session user
    if zenity --question --title="🛡️ Escudo de Seguridad" \
        --text="Han pasado más de 7 días desde tu última auditoría de seguridad.\n\n¿Deseas iniciar un escaneo de malware y rootkits ahora mismo?" \
        --width=400 2>/dev/null; then
        
        # Launch with pkexec passing display variables so Zenity GUI displays properly on Wayland/X11
        pkexec env DISPLAY="$DISPLAY" XAUTHORITY="${XAUTHORITY:-}" WAYLAND_DISPLAY="$WAYLAND_DISPLAY" XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" /usr/local/bin/security-scan
    fi
fi
EOF
chmod +x "$CHECK_BIN"


# Install GNOME autostart file for the original non-root user
if [ -n "${SUDO_USER:-}" ]; then
    USER_HOME=$(eval echo "~$SUDO_USER")
    AUTOSTART_DIR="${USER_HOME}/.config/autostart"
    AUTOSTART_FILE="${AUTOSTART_DIR}/security-check.desktop"
    
    mkdir -p "$AUTOSTART_DIR"
    cat << EOF > "$AUTOSTART_FILE"
[Desktop Entry]
Type=Application
Name=Security Check
Comment=Prompts to scan system if last check is older than 7 days
Exec=$CHECK_BIN
Icon=security-high-symbolic
Terminal=false
Categories=System;Security;
X-GNOME-Autostart-enabled=true
EOF
    chown -R "$SUDO_USER":"$SUDO_USER" "$AUTOSTART_DIR"
    log_success "Weekly check integrated into GNOME autostart for user: $SUDO_USER."
    
    # Initialize the last run file so it doesn't prompt immediately after install
    if [ ! -f "/var/log/security_last_run" ]; then
        date +%s > /var/log/security_last_run
        chmod 644 /var/log/security_last_run
    fi
else
    log_warn "SUDO_USER not detected. GNOME autostart not registered. Scanners are configured under /usr/local/bin/."
fi


# 9. Sandbox de Aplicaciones Nativas (Firejail & Firetools GUI)
log_info "Configuring application isolation sandboxing (Firejail & Firetools)..."
if ! command -v firejail &>/dev/null || ! command -v firetools &>/dev/null; then
    log_info "Firejail or Firetools GUI not found. Installing via pacman..."
    pacman -S --needed --noconfirm firejail firetools
fi

# Run firecfg to automatically integrate standard desktop applications
log_info "Registering desktop apps to use Firejail sandboxing dynamically..."
firecfg >/dev/null 2>&1 || log_warn "Some applications could not be symlinked to Firejail automatically."
log_success "Firejail & Firetools GUI installed and integrated with GNOME Desktop."

echo ""
log_success "💡 Hardened Security Standard module completed!"
log_info "Pro-tips for system defense:"
log_info "  - Run 'sudo lynis audit system' to perform an in-depth security analysis."
log_info "  - Run 'clamscan -r --bell -i /home' to scan your home folder for malware."
log_info "  - Run 'sudo rkhunter --check' to perform a rootkit & exploit scan."
log_info "  - Scanners are automated to prompt you once a week upon logging into GNOME!"
log_info "  - Launch 'firetools' from GNOME menu to visually manage your isolated app sandboxes!"





